sudo: required
services:
  - docker

before_install:
  - docker build -t sathishg2585/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sathishg2585/react-test npm test -- --coverage

after_success:
  - docker build -t sathishg2585/multi-client ./client
  - docker build -t sathishg2585/multi-nginx ./nginx
  - docker build -t sathishg2585/multi-server ./server
  - docker build -t sathishg2585/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sathishg2585/multi-client
  - docker push sathishg2585/multi-nginx
  - docker push sathishg2585/multi-server
  - docker push sathishg2585/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: Multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-eu-west-2-253430545278
  bucket_path: Multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

